#!/bin/bash
export ORG_NAME="ian-org"
export ORG_ID="132638132450"
export PROJECT_NAME="My First Project"
export PROJECT_NUMBER="860809078168"
export PROJECT_ID="project-7b23314a-3205-4a62-b83"
export BILLING_NAME="billing"
export BILLING_NUMBER="601945094541"
export BILLING_ID="billing-507309"
export REGION="europe-west2"

echo "Setting the following variables:"
echo "ORG_NAME=$ORG_NAME"
echo "ORG_ID=$ORG_ID"
echo "PROJECT_NAME=$PROJECT_NAME"
echo "PROJECT_NUMBER=$PROJECT_NUMBER"
echo "PROJECT_ID=$PROJECT_ID"
echo "BILLING_NAME=$BILLING_NAME"
echo "BILLING_NUMBER=$BILLING_NUMBER"
echo "BILLING_ID=$BILLING_ID"
echo "REGION=$REGION"
echo
